apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app
spec:
  destination:
    name: ''
    namespace: argocd-apps
    server: 'https://kubernetes.default.svc'
  source:
    path: overlays/dev-2
    repoURL: 'https://github.com/bekzatbaubek/kustomize.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
