---
resources:
- ../../base

namePrefix: dev-2-

images:
- name: nginx
  newTag: 1.8.0

patches:
- path: nginx.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-deployment
